AWSTemplateFormatVersion: '2010-09-09'
Description: StayHome DevKit - EC2 Instance for user

# ------------------------------------------------------------#
#  EC2 Instance
# ------------------------------------------------------------# 

Metadata: 
  "AWS::CloudFormation::Interface": 
    ParameterGroups: 
      - Label: 
          default: "Project Name Prefix"
        Parameters: 
          - PJPrefix
          - UserName

Parameters:
  PJPrefix:
    Type: String
        # Replace to your own project name string
    Default : {PROJECT_NAME}

  UserName:
    Type: String
        # Replace to your own project name string
    Default : {USER_NAME}

  InstanceType:
    Type: String
    Default: t2.micro
  ImageId:
    Type:  AWS::EC2::Image::Id
    Default: ami-093b908b31745fa80
  KeyName:
    Type: AWS::EC2::KeyPair::KeyName  
    Default: {USER_NAME}

Resources:
  EC2Instance:
      Type: AWS::EC2::Instance
      Properties:
        InstanceType: !Ref InstanceType
        ImageId: !Ref ImageId
        KeyName: !Ref KeyName
        Monitoring: true
        SecurityGroupIds: 
          - { "Fn::ImportValue": !Sub "SecurityGroup-${PJPrefix}" }
        SubnetId: { "Fn::ImportValue": !Sub "Subnet-${PJPrefix}" }
        Tags:
          - Key: Name
            Value: !Sub ${UserName}

  EC2ElasticIp:
    Type: AWS::EC2::EIP
    Properties:
      InstanceId: !Ref EC2Instance
      Domain: vpc